<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  <?=$this->_translation->translate('About');?>
</h1>

<a href="http://code.google.com/p/php-by-example/"><?=$this->_translation->translate('Source code');?></a>
<br />
<a href="http://statcounter.com/p9559234/summary/?guest=1"><?=$this->_translation->translate('Stats');?></a>
<br />
<a href="<?=$this->_output->display_url('test_all');?>"><?=$this->_translation->translate('Test of all functions');?></a>
