<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  <?=$this->_output->display_custom_function_title($this->_application->function_basename, $this->filename, $this->type);?>
  <?php require "$this->application_path/views/english_only.phtml";?>
</h1>

<?php if ($this->error):?>
  <span class="red"><?=$this->error;?></span>

<?php else:?>
  <div class="custom_function blue_border"><?php highlight_file($this->filepath);?></div>

<?php endif;?>
