<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<?php if ($this->_language->language_id != 'en' or $this->_params->translation_in_action == 2401):?>

  <span class="english_only">
    <?=$this->_translator->translate('This page is available in English only.');?>
  </span>

<?php endif;?>
