<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  <?=$this->_translation->translate('List of available functions');?> (<?=count($this->_function_list->function_list);?>)
</h1>

<?php foreach($this->_function_list->function_list as $function_name):?>
  <div>
    <a href="<?=$this->_output->display_url('function', $function_name);?>"><?=$function_name;?></a>
  </div>
<?php endforeach;?>
