<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<div class="title <?=$color;?>"><?=$title;?></div>

<div class="block <?=$color;?>_border">
  <?php foreach($functions as $function_basename => $function_name):?>

    <?php if ($function_name != current($functions)):?>,<?php endif;?>

    <a href="<?=$this->display_url('test', $function_basename);?>"><?=$function_name;?></a>

  <?php endforeach;?>
</div>
