<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  <?=$this->_translation->translate('Welcome to the world of the PHP functions');?>
</h1>

<?=$this->_translation->translate('Here you can test PHP functions online.');?><br />
<?=$this->_translation->translate("You won't have to write a single line of code.");?><br />
<?=$this->_translation->translate('You just need to select a function to get the result.');?><br />
<br />
<?=$this->_translation->translate('Each function comes with a few examples.');?><br />
<?=$this->_translation->translate('You may of course change the function arguments at will.');?><br />
<?=$this->_translation->translate('The corresponding page of the manual is also displayed automatically.');?><br />
<br />
<?=$this->_translation->translate('So go ahead, and start playing...');?>
<br />
<br />
<a href="<?=$this->_output->display_url('function_list');?>"><?=$this->_translation->translate('List of available functions');?></a>
(<?=count($this->_function_list->function_list);?>)

