<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>PHP By Example</title>
    <link rel="stylesheet" type="text/css" href="<?=$this->base_url;?>/interface.css" />
  </head>

  <body <?php if ($this->_params->search_method == 'input'):?>
           onload="set_function_input('<?=$this->_synopsis->function_name;?>'); set_php_manual_size(<?=(int) ($this->_params->php_manual_location == 'local_copy');?>)"
        <?php else:?>
           onload="set_function_select('<?=$this->_synopsis->function_name;?>'); set_php_manual_size(<?=(int) ($this->_params->php_manual_location == 'local_copy');?>)"
        <?php endif;?>

        onresize="set_php_manual_size(<?=(int) ($this->_params->php_manual_location == 'local_copy');?>)">

    <?php require "$this->application_path/views/top_bar.phtml";?>
    <?php require "$this->application_path/views/{$this->action_name}.phtml";?>
    <?php require "$this->application_path/views/bottom_bar.phtml";?>

    <script type="text/javascript" src="<?=$this->base_url;?>/interface.js"></script>
    <script type="text/javascript" src="<?=$this->base_url;?>/function_list.js?v=<?=$this->_function_list->function_list_mtime;?>"></script>

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
//<![CDATA[
var sc_project=9559234;
var sc_invisible=1;
var sc_security="a5353179";
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter_xhtml.js'></"+"script>");
//]]>
</script>
<noscript><div class="statcounter"><a title="web analytics"
href="http://statcounter.com/" class="statcounter"><img
class="statcounter"
src="http://c.statcounter.com/9559234/0/a5353179/1/"
alt="web analytics" /></a></div></noscript>
<!-- End of StatCounter Code for Default Guide -->

  </body>
</html>
