<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  Misc
  <?php require "$this->application_path/views/english_only.phtml";?>
</h1>

<a href="<?=$this->_output->display_url('test_all');?>">Test of all functions</a>
<br />
<a href="<?=$this->_output->display_url('unit_test');?>">Unit tests</a>
<br />
<br />
<a href="<?=$this->_output->display_url('messages_translation');?>">Translation of messages</a>
<br />
<a href="<?=$this->_output->display_url('translations_stats');?>">Translation stats</a>
<br />
<a href="<?=$this->_output->display_url('translators_stats');?>">Translators stats</a>
<br />
<br />
<a href="http://code.google.com/p/php-by-example/">Source code</a>
<br />
<a href="http://statcounter.com/p9559234/summary/?guest=1">Stats</a>
