<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */

$php_manual_locations = [
    'local_copy'   => $this->_translator->translate('Local copy of PHP manual'),
    'php.net'      => $this->_translator->translate('PHP Manual at php.net'),
    'none'         => $this->_translator->translate('No display of PHP manual'),
];
?>

<select class="blue"
        id="php_manual_location"
        onchange="change_php_manual_location(this)">

  <?php foreach($php_manual_locations as $location_id => $location_name) :?>
  <option <?php if($location_id == $this->_params->php_manual_location):?>selected="selected"<?php endif;?>
          value="<?=$location_id;?>">
      <?=$location_name;?>
  </option>
  <?php endforeach;?>

</select>
