<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<?php if ($this->_params->php_manual_location != 'none'):?>

  <?php if ($url = $this->_output->display_function_manual_page_url() and ! in_array($this->_params->translation_in_action, [2501, 2502])):?>
    <iframe id="php_manual"
            onload="set_php_manual_size(<?=(int) ($this->_params->php_manual_location == 'local_copy');?>)"
            src="<?=$url;?>"></iframe>

  <?php else:?>
    <div class="block red_border red">
        <?=$this->_translator->translate('This page of the PHP manual is not available.');?>
        <?=$this->_translator->translate('Sorry for the inconvenience.');?>
    </div>
  <?php endif;?>

<?php endif;?>
