<?php
/**
 * PHP By Example
 *
 * @copyright 2014 Michel Corne <mcorne@yahoo.com>
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<?php if ($this->_params->php_manual_location != 'none'):?>

  <?php if ($url = $this->_output->display_function_manual_page_url() and ! in_array($this->_params->translation_in_action, [2501, 2502])):?>

    <?php if ($this->_params->php_manual_location == 'php.net'):?>
      <div id="php_manual_new_tab" style="display:none"><?=$url;?></div>

    <?php else:?>
      <iframe id="php_manual"
              onload="set_php_manual_size()"
              src="<?=$url;?>"></iframe>
    <?php endif;?>

  <?php else:?>
    <div class="block red_border red">
        <?=$this->_message_translation->translate('This page of the PHP manual is not available.');?>
        <?=$this->_message_translation->translate('Sorry for the inconvenience.');?>
    </div>
  <?php endif;?>

<?php endif;?>
