<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<div class="title <?=$color;?>"><?=$title;?></div>

<div class="block <?=$color;?>_border">
  <?php foreach ($functions as $function_basename => $function_name):?>

    <span class="nowrap">

      <a href="<?=$this->display_url('test', $function_name);?>"><?=$function_name;?></a>

      <?php if (! empty($test_count_by_function[$function_basename])):?>

        <?php if (isset($test_subset_count_by_function[$function_basename])):?>
          <span class="gray">(<?=($test_subset_count_by_function[$function_basename]);?>/<?=($test_count_by_function[$function_basename]);?>)</span>
        <?php else:?>
          <span class="gray">(<?=($test_count_by_function[$function_basename]);?>)</span>
        <?php endif;?>

      <?php endif;?>

      <?php if ($function_name != $last_function_name):?>,<?php endif;?>

    </span>

  <?php endforeach;?>
</div>
