<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  Test of <?=$this->_output->display_function_name();?>
  <?php require "$this->application_path/views/english_only.phtml";?>
</h1>

<?php require "$this->application_path/views/php_manual.phtml";?>

<div class="block blue_border">
  <table>

    <?php foreach($this->test_validations as $example_id => $validation):
              $status = $validation['status'];?>
      <tr>

        <td>Example <?=$example_id;?></td>

        <td>:</td>

        <td>
          <?php if ($status === true):?>
            <span class="green">test success</span>
          <?php elseif ($status === false):?>
            <span class="red">test failed</span>
          <?php else:?>
            <span class="orange">test missing</span>
          <?php endif;?>
        </td>

      </tr>
    <?php endforeach;?>

  </table>
</div>

<?php if ($this->obsolete_expected_results) :?>

  <div class="block red_border">
    <div>
      <span class="red">Warning! </span>
      There is one or more obsolete expected test results, please remove or fix !
    </div>
  </div>

<?php endif;?>

<?php foreach($this->test_validations as $example_id => $validation):
          $status = $validation['status'];?>

  <?php if ($status === true):?>
    <div class="title green">Example <?=$example_id;?></div>
    <div class="block green_border">

  <?php elseif ($status === false):?>
    <div class="title red">Example <?=$example_id;?></div>
    <div class="block red_border">

  <?php else:?>
    <div class="title orange">Example <?=$example_id;?></div>
    <div class="block orange_border">
  <?php endif;?>

    <table>

       <tr>
         <td class="variable">$input</td>
         <td class="operator">=</td>
         <td><?=$this->_output->display_var_value($this->examples[$example_id]);?></td>
       </tr>

       <tr>
         <?php if ($status !== null):?>
           <td class="variable">$expected_output</td>
         <?php else:?>
           <td class="orange">$expected_output</td>
         <?php endif;?>

         <td class="operator">=</td>

         <?php if ($status === true):?>
           <td class="variable">$test_output</td>
         <?php elseif ($status === false):?>
           <td><?=$this->_output->display_var_value($validation['expected_result']);?></td>
         <?php else:?>
           <td>MISSING</td>
         <?php endif;?>
       </tr>

       <tr>
         <?php if ($status === true):?>
           <td class="green">$test_output</td>
         <?php elseif ($status === false):?>
           <td class="red">$test_output</td>
         <?php else:?>
           <td class="variable">$test_output</td>
         <?php endif;?>

         <td class="operator">=</td>

         <td><?=$this->_output->display_var_value($validation['test_result']);?></td>
       </tr>

     </table>
  </div>

<?php endforeach;?>

<?php require "$this->application_path/views/php_manual_location.phtml";?>
