<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  Test of all functions
  <?php require "$this->application_path/views/english_only.phtml";?>
</h1>

<div class="block blue_border">
  <table>

    <tr>
      <td class="green">Functions tested successfully<td>
      <td class="blue"><?=count($this->test_results['functions_tested_succesfully']);?><td>
    </tr>

    <tr>
      <td class="red">Functions with failed tests<td>
      <td class="blue"><?=count($this->test_results['functions_with_failed_tests']);?><td>
    </tr>

    <tr>
      <td class="orange">Functions with missing tests<td>
      <td class="blue"><?=count($this->test_results['functions_with_missing_tests']);?><td>
    </tr>

    <tr>
      <td class="orange">Functions with obsolete tests<td>
      <td class="gray"><?=count($this->test_results['functions_with_obsolete_tests']);?><td>
    </tr>

    <tr>
      <td class="gray">Functions not tested<td>
      <td class="gray"><?=count($this->test_results['functions_not_tested']);?><td>
    </tr>

    <tr>
      <td class="gray">Functions not available<td>
      <td class="gray"><?=count($this->test_results['functions_not_available']);?><td>
    </tr>

  </table>
</div>

<?php $this->test_results['functions_tested_succesfully'] and
      $this->_output->display_function_list($this->test_results['functions_tested_succesfully'], 'Functions tested successfully', 'green');?>

<?php $this->test_results['functions_with_failed_tests'] and
      $this->_output->display_function_list($this->test_results['functions_with_failed_tests'], 'Functions with failed tests', 'red');?>

<?php $this->test_results['functions_with_missing_tests'] and
      $this->_output->display_function_list($this->test_results['functions_with_missing_tests'], 'Functions with missing tests', 'orange');?>

<?php $this->test_results['functions_with_obsolete_tests'] and
      $this->_output->display_function_list($this->test_results['functions_with_obsolete_tests'], 'Functions with obsolete tests', 'orange');?>

<?php $this->test_results['functions_not_tested'] and
      $this->_output->display_function_list($this->test_results['functions_not_tested'], 'Functions not tested', 'gray');?>

<?php $this->test_results['functions_not_available'] and
      $this->_output->display_function_list($this->test_results['functions_not_available'], 'Functions not available', 'gray');?>
