<?php
/**
 * PHP By Example
 *
 * @author    Michel Corne <mcorne@yahoo.com>
 * @copyright 2014 Michel Corne
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<div>

  <a class="logo"
     href="<?=$this->_output->display_url();?>"
    ><img src="<?=$this->base_url;?>/logo.gif"
    /> by Example</a>

  <datalist id="function_list"><option></option></datalist>
  <input id="function_input"
         list="function_list"
         onkeypress="is_enter_key(event) && run_function('<?=$this->_output->display_url('function');?>')"
         value="<?=$this->_synopsis->function_name;?>" />

  <span id="function_select_placeholder"><select id="function_select"><option><?=$this->_synopsis->function_name;?></option></select></span>

  <input class="button select"
         onclick="run_function('<?=$this->_output->display_url('function');?>')"
         type="button"
         value="<?=$this->_translation->translate('Choose a function');?>" />

</div>

<hr />
