<?php
/**
 * PHP By Example
 *
 * @copyright 2014 Michel Corne <mcorne@yahoo.com>
 * @license   http://www.opensource.org/licenses/gpl-3.0.html GNU GPL v3
 */
?>

<h1>
  Unit test of
  <?php require "$this->application_path/views/unit_test_selection.phtml";?>
  <?php require "$this->application_path/views/english_only.phtml";?>
</h1>

<?php $this->_application->function_name and require "$this->application_path/views/php_manual.phtml";?>

<div class="block blue_border">

  <?php if (! $this->class_test_results):?>
    <span class="gray">There is no method to test in this class.</span>

  <?php else:?>
    <?php require 'unit_test_summary.phtml';?>
  <?php endif;?>

</div>

<?php $this->class_test_results and require 'unit_test_details.phtml';?>